services:
  app:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
    - unleash
  unleash:
    image: unleashorg/unleash-server:latest
    ports:
      - 4242:4242
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://unleash_user:unleash_pass@postgres:5432/unleash_db
      DATABASE_SSL: "false"
      BASE_URI_PATH: /unleash
      LOG_LEVEL: "info"
      INIT_FRONTEND_API_TOKENS: "default:development.unleash-frontend-api-insecure-token"
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: unleash_user
      POSTGRES_PASSWORD: unleash_pass
      POSTGRES_DB: unleash_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U unleash_user -d unleash_db"]
      interval: 1s
      timeout: 15s
      retries: 15



